"""
Django settings for pehchano project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@^wx@v41es)jfg7f_(1#q==&2slhkz9g@qa8x5$3%m6)u!$^4w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # django-allauth apps for authentication
    'allauth',  # Core allauth package
    'allauth.account',  # Account management (login, signup, password reset)
    'allauth.socialaccount',  # If you're using social account integration (optional)

    # Built-in Django apps
    'django.contrib.admin',  # Django admin panel for managing the site
    'django.contrib.auth',  # Authentication system
    'django.contrib.contenttypes',  # Content types for Django ORM (important for models)
    'django.contrib.sessions',  # Session management
    'django.contrib.messages',  # Message framework for displaying messages to users
    'django.contrib.staticfiles',  # Static files handling

    # Your custom app
    'users',  # The app containing your custom user model and views
]

AUTHENTICATION_BACKENDS = (
    'allauth.account.auth_backends.AuthenticationBackend',
)
# Add the following in settings.py

# Custom user model settings
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # No username field
ACCOUNT_LOGIN_METHODS = ['email']  # Allow login using email only
ACCOUNT_SIGNUP_FIELDS = ['email', 'password1', 'password2']  # Sign-up fields: email and password

# Remove deprecated settings
ACCOUNT_EMAIL_REQUIRED = True  # You still need the email for registration and login
ACCOUNT_USERNAME_REQUIRED = False  # We won't use the username for login

# Set the default primary key type for your models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'pehchano.urls'
LOGIN_REDIRECT_URL = '/'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR, 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pehchano.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "users/static"]


AUTH_USER_MODEL = 'users.CustomUser'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'tanzil.ovi578@gmail.com'
EMAIL_HOST_PASSWORD = 'plpz lgjx yhfs ezoi'
DEFAULT_FROM_EMAIL = 'tanzil.ovi578@gmail.com'
CONTACT_EMAIL = 'tanjil.ivo@gmail.com'

# Disable SSL verification for testing (NOT recommended for production)
import smtplib
import ssl
ssl._create_default_https_context = ssl._create_unverified_context